[package]
name = "pixrium"
version = "0.1.0"
edition = "2024"

[dependencies]
freya = { version = "0.4.0-rc.1", features = ["devtools"] }
freya-core = { version = "0.4.0-rc.1" }
freya-icons = { version = "0.4.0-rc.1", features = ["all"] }
skia-safe = { version = "0.91", features = ["gl", "textlayout", "svg"] }
rfd = "0.17"
glam = "0.30"